/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BlogVideo {
        /**
          * The full URL of the video to render in the HTML5 video player.
         */
        "src": string;
    }
}
declare global {
    interface HTMLBlogVideoElement extends Components.BlogVideo, HTMLStencilElement {
    }
    var HTMLBlogVideoElement: {
        prototype: HTMLBlogVideoElement;
        new (): HTMLBlogVideoElement;
    };
    interface HTMLElementTagNameMap {
        "blog-video": HTMLBlogVideoElement;
    }
}
declare namespace LocalJSX {
    interface BlogVideo {
        /**
          * The full URL of the video to render in the HTML5 video player.
         */
        "src"?: string;
    }
    interface IntrinsicElements {
        "blog-video": BlogVideo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "blog-video": LocalJSX.BlogVideo & JSXBase.HTMLAttributes<HTMLBlogVideoElement>;
        }
    }
}
